name: auditoria-fiscal-icms
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - postgresql
  - psycopg2
  - pandas=2.1.3
  - numpy=1.24.3
  - scikit-learn=1.3.2
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - seaborn
  - plotly
  - pip:
    # Web Framework
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - streamlit==1.28.1
    
    # Database
    - sqlalchemy==2.0.23
    - psycopg2-binary==2.9.7
    - alembic==1.12.1
    
    # Authentication & Security
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - python-multipart==0.0.6
    - PyJWT==2.10.1
    
    # Data Processing
    - pydantic[email]==2.5.0
    - openpyxl==3.1.2
    - xlrd==2.0.1
    - python-dotenv==1.0.0
    
    # AI & ML
    - openai==1.3.5
    - anthropic==0.7.7
    - langchain==0.0.340
    - langchain-community==0.0.1
    - chromadb==0.4.18
    - sentence-transformers==2.2.2
    - transformers==4.35.2
    - torch==2.1.1
    - torchvision==0.16.1
    
    # HTTP & API
    - httpx==0.25.2
    - requests==2.31.0
    - aiofiles==23.2.1
    
    # Utilities
    - pyyaml==6.0.1
    - python-dateutil==2.8.2
    - pytz==2023.3
    - tqdm==4.66.1
    
    # Development
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - black==23.11.0
    - flake8==6.1.0
    - mypy==1.7.1
    
    # Documentation
    - mkdocs==1.5.3
    - mkdocs-material==9.4.8
